### ISSUE TITLE
Fetching Text Style Won't Renew Previous Text Style

### ISSUE THREAD

**Issue by YutaAdi** [sigtm/sketch-style-libraries#18] opened 2018-05-16 09:48 UTC
Dear Sigtm,

So I updated text style from my library with certain line heights. When I fetch it from another computer, it doesn't replace the previous version. Instead it duplicates the style (Exact same naming). So I have to manually delete the duplicates and manually click on the new one, which is so frustrating. Please help me solve this issue. Thanks

**Comment by sigtm** [comment] 2018-05-16 16:54
Ooh yeah that sounds annoying. Are you able to consistently reproduce it? If you'd be able to share the files in question it would be super helpful, and maybe your settings from the "Pull styles..." popup?

I haven't seen this problem on my end before, and the plugin matches styles by name so it's a bit worrying if the name matching is broken. Which version of Sketch and Style Libraries are you using?

**Comment by sigtm** [comment] 2018-05-18 07:37
@YutaAdi There was indeed an issue with merging duplicates, which should be fixed in 2.0.4 (just published). It's a bit weird that the plugin would create a duplicate in the first place though, so could you confirm whether you are still experiencing the same problem with the new version?

**Comment by YutaAdi** [comment] 2018-05-21 04:33
Hi @sigtm 
I can merge the styles now, but not always the new one that's on top(if u get what i mean). I set my text style line heights manually, but some merged style came out with default line height. I can send u the sketch via email if it helps.

**Comment by sigtm** [comment] 2018-05-22 16:26
@YutaAdi That would be very helpful, thank you. If you're able to share both the library file and the file you're importing the styles to, I will hopefully be able to figure out what the issue is. You can reach me at mannsaker@gmail.com :)

**Comment by sigtm** [comment] 2018-06-18 14:17
@YutaAdi Not sure if you saw my e-mail, but as far as I can tell the issue was just that there were some duplicate styles in your file (presumably created by the previous version of my plugin). Now that this issue has been fixed, you just have to merge them first and then pull the styles again from the library and you should see the correct line heights etc that you have in your library file.

I'll close this now, but let me know if the issue pops up again and I'll look into it :)

**Closed by sigtm** 2018-06-18 14:17 UTC
Labels: bug

**Comment by YutaAdi** [comment] 2018-06-19 08:15
Hi sigtm,

Yes i've read ur email before. I haven't touch text style so much since my
issue. But I think I've found the way to fix it like u just explained.
Anyway, do u use Abstract?
I'm organizing my files from Abstract now and wondering if fetching or
pushing styles between abstract files is safe.
Will get back to u if I find any problem again

thanks

**Comment by sigtm** [comment] 2018-06-19 08:53
Great, keep me posted if you notice any more hiccups!

My team uses Abstract, although we haven't used libraries much on team projects yet. So I haven't tested as thoroughly there, but it should work just fine.

**Comment by YutaAdi** [comment] 2018-06-22 04:19
Hi sigtm,

How do u fetch styles from abstract files?

**Comment by sigtm** [comment] 2018-06-26 17:33
@YutaAdi Libraries from Abstract should appear in the list just like any other library. Are you able to insert symbols from your library file, but not sync styles?
